Repository CRISalid-esr/svp-harvester, pull requests merged in 2024-02, with the labels that each got.

#257 230 index for abstract
  alembic/versions/9e7b13a24616_remove_abstract_from_inheritance_.py
  app/db/models/abstract.py
  app/db/models/reference_literal_field.py
  app/db/models/subtitle.py
  app/db/models/title.py
Labels: Refacto

#262 225 add support to halid_s and orcid for scanr harvester
  app/harvesters/scanr/scanr_api_query_builder.py
  app/harvesters/scanr/scanr_harvester.py
  docs/build/html/.doctrees/environment.pickle
  docs/build/html/.doctrees/harvesters/scanr.doctree
  docs/build/html/_sources/harvesters/scanr.rst.txt
  docs/build/html/harvesters/scanr.html
  docs/build/html/searchindex.js
  docs/source/harvesters/scanr.rst
  tests/test_api/test_references_harvesters_parameter.py
  tests/test_harvesters/test_scanr/test_scanr_api_query_builder.py
  tests/test_harvesters/test_scanr/test_scanr_harvester.py
Labels: enhancement

#283 Update missing mappings
  app/db/models/contribution.py
  app/harvesters/hal/hal_document_type_converter.py
  app/harvesters/hal/hal_qualitites_converter.py
  app/harvesters/idref/open_edition_document_type_converter.py
  app/harvesters/idref/persee_qualities_converter.py
  app/harvesters/scanr/scanr_roles_converter.py
Labels: Model coverage

#296 266 client system mock
  deploy/k8s-gke/.gitignore
  deploy/k8s-gke/ksa/service-account.yaml
  deploy/k8s-gke/svp/svp-client-mock-cron.yml
  deploy/k8s-gke/svp/svp-rabbit-depl.yaml
  deploy/k8s-gke/svp/svp-rabbit-pvc.yaml
  deploy/k8s-gke/svp/svp-rabbit-secret.yaml.dist
  deploy/k8s-gke/svp/svp-rabbit-svc.yaml
  deploy/k8s-gke/svp/svph-api-config.yaml
  deploy/k8s-gke/svp/svph-api-depl.yaml
  deploy/k8s-gke/svp/svph-api-secret.yaml.dist
  deploy/k8s-gke/svp/svph-api-svc.yaml
  deploy/k8s-gke/svp/svph-db-secret.yaml.dist
  deploy/k8s-minikube/.gitignore
  deploy/k8s-minikube/svp-rabbit-depl.yaml
  deploy/k8s-minikube/svp-rabbit-pvc.yaml
  deploy/k8s-minikube/svp-rabbit-secret.yaml.dist
  deploy/k8s-minikube/svp-rabbit-svc.yaml
  deploy/k8s-minikube/svph-api-config.yaml
  deploy/k8s-minikube/svph-api-depl.yaml
  deploy/k8s-minikube/svph-api-ing.yaml
  deploy/k8s-minikube/svph-api-secret.yaml.dist
  deploy/k8s-minikube/svph-api-svc.yaml
  deploy/k8s-minikube/svph-db-depl.yaml
  deploy/k8s-minikube/svph-db-pvc.yaml
  deploy/k8s-minikube/svph-db-secret.yaml.dist
  deploy/k8s-minikube/svph-db-svc.yaml
  deploy/k8s-minikube/svph-user-db.sql.dist
  scripts/client_system_mock/Dockerfile
  scripts/client_system_mock/fetch_ids.py
  scripts/client_system_mock/fetch_pubs.py
  scripts/client_system_mock/poetry.lock
  scripts/client_system_mock/pyproject.toml
  scripts/client_system_mock/requirements.txt
Labels: CI/CD

#301 274 external endpoint failure not retrieved for openedition
  app/harvesters/abstract_references_converter.py
  app/harvesters/idref/idref_harvester.py
  app/harvesters/idref/idref_sparql_client.py
  app/harvesters/idref/resolver_http_client.py
  app/harvesters/scanr/scanr_references_converter.py
  poetry.lock
  tests/data/hal_api/docs_with_inconsistent_contributors.json
  tests/fixtures/hal_api_docs_fixtures.py
  tests/test_api/test_inconsistent_contributors.py
  tests/test_services/test_concepts/test_concept_factory.py
  tests/test_services/test_concepts/test_idref_concept_solver.py
  tests/test_services/test_concepts/test_idref_concept_solver_integration.py
Labels: bug

#312 Remove erroneous import
  app/services/concepts/concept_solver_rdf.py
Labels: bug, CI/CD

#324 Performance enhancements
  app/db/daos/reference_event_dao.py
  app/db/daos/retrieval_dao.py
  app/db/models/reference.py
  deploy/k8s-gke/svp/svph-api-depl.yaml
  tests/test_harvesters/test_hal/test_hal_harvester.py
Labels: Performance

#327 Fix erroneous query
  app/amqp/amqp_reference_event_message_factory.py
  app/db/daos/reference_event_dao.py
Labels: bug
